default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_task_training_development

test:
  <<: *default
  database: my_task_training_test

production:
  <<: *default
  database: my_task_training_production
